- hosts: localhost 
  connection: local 
  become: true

  pre_tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

  tasks:
    - include_tasks: tasks/packages.yml
