---
- hosts: localhost 
  connection: local 
  vars_files:
    - vars.yml
  become: true

  tasks:
    - include_tasks: tasks/repos.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml 
    - include_tasks: tasks/copy_configs.yml
    - include_tasks: tasks/system.yml
