---
- hosts: localhost 
  connection: local 
  vars_files:
    - vars.yml
  become: true

  pre_tasks:
    - include_tasks: tasks/dnf.yml
    - name: Upgrade first
      ansible.builtin.dnf:
        name: "*"
        state: latest
        use_backend: dnf4

  tasks:
    - include_tasks: tasks/dnf.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml 
    - include_tasks: tasks/copy_configs.yml
    - include_tasks: tasks/system.yml

  post_tasks:
    - name: Copy Zshrc
      ansible.builtin.file:
        src: files/.zshrc 
        dest: "/home/{{ primary_user }}/.zshrc"
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"
        state: link
