---

- hosts: localhost 
  connection: local 
  vars_files:
    - vars.yml
  become: true

  tasks:
    - name: Install Oh-My-Zsh 
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
      become: true
      become_user: "{{ primary_user }}"
      when: shell == "/usr/bin/zsh"

    - name: Link Config Files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/.config"
        dest: "/home/{{ primary_user}}/.config"
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"
        state: link

    - name: Link .zshrc 
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/.zshrc"
        dest: "/home/{{ primary_user }}/.zshrc"
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"
        state: link 

    - name: Change hostname 
      ansible.builtin.hostname: 
        name: "{{ hostname }}"

    - name: Create primary_user and assign preferred shell
      user:
        name: "{{ primary_user }}"
        shell: "{{ shell }}"

    - name: Run gtk.sh to install Catppuccin GTK theme 
      ansible.builtin.shell: "/home/{{ primary_user }}/.config/config_scripts/gtk.sh"
      args:
        creates: "/home/{{ primary_user }}/.config/gtk-3.0"
      become: true
      become_user: "{{ primary_user }}"
