- hosts: localhost 
  connection: local 
  become: true

  pre_tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Create config dir
      ansible.builtin.file:
        path: /home/aj/.config
        state: directory
        mode: '0755'
        owner: aj
        group: aj 

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml 
    - include_tasks: tasks/cron.yml
