---
- hosts: localhost 
  connection: local 
  vars_files:
    - vars.yml
  become: true

  pre_tasks:
    - name: Distupgrade first
      community.general.zypper:
        name: "*"
        state: dist-upgrade
        allow_vendor_change: true

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml 
    - include_tasks: tasks/copy_configs.yml
    - include_tasks: tasks/system.yml

  post_tasks:
    - name: Copy Zshrc
      ansible.builtin.copy:
        src: files/.zshrc 
        dest: "/home/{{ primary_user }}/.zshrc"
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"
        mode: u=rw,g=r,o=r

