- hosts: localhost 
  connection: local 
  vars_files:
    - vars.yml
  become: true

  tasks:
    - name: Install preferred shell
      ansible.builtin.apt: 
        name: "{{ preferred_shell }}"
        state: latest

    - name: Get path to preferred shell 
      ansible.builtin.shell: command -v "{{ preferred_shell }}"
      register: shell_path

    - name: Create groups for user 
      ansible.builtin.group:
        name: libvirt 
        state: present

    - name: Create groups for user 
      ansible.builtin.group:
        name: qemu 
        state: present

    - name: Create primary_user with preferred_shell
      user: 
        name: "{{ primary_user }}"
        shell: "{{ shell_path.stdout }}"
        groups: 
          - libvirt
          - qemu
          - sudo 

    - name: Install the nas system if requested
      include_tasks: systems/nas.yml
      when: system_type == "nas"

    - name: Install the desktop system if requested
      include_tasks: systems/desktop.yml
      when: system_type == "desktop"

    - name: Install the laptop system if requested
      include_tasks: systems/laptop.yml
      when: system_type == "laptop"

    - name: Change hostname 
      ansible.builtin.hostname: 
        name: "{{ hostname }}"

    - name: Enable Tailscaled
      ansible.builtin.systemd_service:
        name: tailscaled
        state: started
        enabled: true

    - name: Enable libvirtd 
      ansible.builtin.systemd_service: 
        name: libvirtd 
        state: started 
        enabled: true 

    - name: Make sure default libvirt net starts at boot
      ansible.builtin.shell: virsh net-autostart default

          # - name: Enable plocate-updatedb 
          #   ansible.builtin.systemd_service: 
          #     name: plocate-updatedb.timer 
          #     state: started 
          #     enabled: true 

        # - include_tasks: tasks/repos.yml
        # - include_tasks: tasks/packages.yml
        # - include_tasks: tasks/system.yml
        # - include_tasks: tasks/extra_packages.yml
