- name: Copy Config Files
  copy:
    src: files/.config
    dest: /home/aj/
    owner: aj
    group: aj
    mode: '0644'

- name: Make River config executable 
  ansible.builtin.file:
    path: /home/aj/.config/river/init 
    owner: aj
    group: aj
    mode: '0755'

- name: Make config scripts executable
  ansible.builtin.file:
    path: /home/aj/.config/config_scripts/
    owner: aj
    group: aj
    mode: '0755'

- name: Run make-rofi-config script 
  ansible.builtin.shell: files/.config/config_scripts/make-rofi-config.sh
  args:
    chdir: /home/aj/.config/
