- name: Copy Config Files
  copy:
    src: files/.config
    dest: /home/aj/
    owner: aj
    group: aj
    mode: '0644'

- name: Set River init file to executable
  ansible.builtin.file:
    path: /home/aj/.config/river/init 
    owner: aj
    group: aj
    mode: '0755'

- name: Set Rofi config script to executable 
  ansible.builtin.file:
    path: /home/aj/.config/config_scripts/rofi-config.sh
    owner: aj
    group: aj
    mode: '0755'

- name: Install Oh-My-Zsh 
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

