- name: Copy Config Files
  copy:
    src: files/.config
    dest: /home/aj/
    owner: aj
    group: aj
    mode: '0644'

- name: Set River init file to executable
  ansible.builtin.file:
    path: /home/aj/.config/river/init 
    owner: aj
    group: aj
    mode: '0755'

- name: Set make-rofi-config.sh to executable
  ansible.builtin.file:
    path: /home/aj/.config/config_scripts/make-rofi-config.sh
    owner: aj
    group: aj
    mode: '0755'

- name: Set vars.sh to executable 
  ansible.builtin.file:
    path: /home/aj/.config/config_scripts/vars.sh
    owner: aj
    group: aj
    mode: '0755'

- name: Run make-rofi-config script 
  ansible.builtin.shell: /home/aj/.config/config_scripts/make-rofi-config.sh
  args:
    chdir: /home/aj/.config/config_scripts/
