--- 

- name: Check if .zshrc already exists
  stat:
    path: "/home/{{ primary_user }}/.zshrc"
  register: result

- name: Move existing .zshrc 
  ansible.builtin.command: "mv /home/{{ primary_user }}/.zshrc /home/{{ primary_user }}/.zshrc.pre-provision"
  when: result.stat.exists

- name: Link zshrc 
  ansible.builtin.file: 
    src: "{{ playbook_dir }}/files/.zshrc"
    dest: "/home/{{ primary_user }}/.zshrc"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    state: link

- name: Check if .config already exists
  stat:
    path: "/home/{{ primary_user }}/.config"
  register: result

- name: Move existing .config
  ansible.builtin.command: "mv /home/{{ primary_user }}/.config /home/{{ primary_user }}/.config.pre-provision"
  when: result.stat.exists

- name: Link .config dir 
  ansible.builtin.file: 
    src: "{{ playbook_dir }}/files/.config"
    dest: "/home/{{ primary_user }}/.config"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    state: link

- name: Run gtk.sh to install Catppuccin GTK theme 
  ansible.builtin.shell: "/home/{{ primary_user }}/.config/config_scripts/gtk.sh"
  args:
    creates: "/home/{{ primary_user }}/.config/gtk-3.0"
  become: true
  become_user: "{{ primary_user }}"

- name: Run node_config.sh to install NVM and Node.JS 
  ansible.builtin.shell: "/home/{{ primary_user }}/.config/config_scripts/node_config.sh"
  args:
    creates: "/home/{{ primary_user }}/.nvm"
  become: true
  become_user: "{{ primary_user }}"
