- name: Copy Config Files
  copy:
    src: files/.config
    dest: /home/aj/
    owner: aj
    group: aj
    mode: '0644'

- name: Make River config executable 
  ansible.builtin.file:
    path: /home/aj/.config/river/init 
    owner: aj
    group: aj
    mode: '0755'
