- name: Copy Alacritty Config 
  copy:
    src: files/alacritty.yml
    dest: /home/aj/.config/alacritty.yml
    owner: aj
    group: aj
    mode: '0644'

- name: Copy River Config
  copy:
    src: files/river
    dest: /home/aj/.config/
    owner: aj
    group: aj
    mode: '0755'

- name: Copy Dunst Config 
  copy:
    src: files/dunst 
    dest: /home/aj/.config/
    owner: aj
    group: aj
    mode: '0755'
