---

- name: DNF Makecache 
  ansible.builtin.shell: dnf makecache 

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base packages 
  ansible.builtin.dnf:
    name:
      - "@Development Tools"
      - alacritty
      - ansible
      - bluez
      - bluez-tools
      - cascadia-code-pl-fonts
      - dbus-daemon
      - dbus-tools
      - dunst
      - firefox
      - gimp
      - gnome-keyring
      - google-noto-emoji-fonts
      - gvfs-mtp
      - grim
      - grimshot
      - jmtpfs
      - keepassxc
      - kpcli
      - ledger
      - libreoffice
      - lxpolkit
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pavucontrol
      - pipewire
      - playerctl
      - polkit
      - protonvpn-cli
      - ranger
      - river
      - river-bsp-layout
      - ripgrep
      - rofi-wayland
      - rpmdevtools
      - rpmlint
      - rustup
      - swaybg
      - swayidle
      - swaylock
      - tailscale
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - torbrowser-launcher
      - unzip
      - vlc
      - waybar
      - wireplumber
      - wl-clipboard
      - wlr-randr
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - xorg-x11-server-Xwayland
      - zip
      - zsh
      - zsh-autosuggestions
    state: latest

- name: Autoremove unneeded packages 
  ansible.builtin.dnf: 
    autoremove: true

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"

- name: Run rustup-init
  ansible.builtin.shell: rustup-init --default-host x86_64-unknown-linux-gnu --profile default --default-toolchain stable -y
  become: true 
  become_user: "{{ primary_user }}"
