- name: Add tailscale repo 
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    async: true 
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    enabled: true 
    state: present 
    gpgcheck: true 
    repo_gpgcheck: true 
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg

- name: Import RPM Fusion GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop:
    - "https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Enable the RPM Fusion repository
  ansible.builtin.dnf:
    name: 
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install base packages 
  ansible.builtin.dnf:
    name:
      - "@Development Tools"
      - alacritty
      - ansible
      - bluez
      - bluez-tools
      - cascadia-code-pl-fonts
      - dbus-daemon
      - dbus-tools
      - dunst
      - firefox
      - gimp
      - gnome-keyring
      - google-noto-emoji-fonts
      - gvfs-mtp
      - grim
      - grimshot
      - jmtpfs
      - keepassxc
      - kpcli
      - ledger
      - libreoffice
      - lxpolkit
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pavucontrol
      - pipewire
      - playerctl
      - polkit
      - ranger
      - river
      - ripgrep
      - rofi-wayland
      - rpmdevtools
      - rpmlint
      - rustup
      - swaybg
      - swayidle
      - swaylock
      - tailscale
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - torbrowser-launcher
      - unzip
      - vlc
      - waybar
      - wireplumber
      - wl-clipboard
      - wlr-randr
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - xorg-x11-server-Xwayland
      - zip
      - zsh
      - zsh-autosuggestions
    state: latest

- name: Autoremove unneeded packages 
  ansible.builtin.dnf: 
    autoremove: true

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"

- name: Run rustup-init
  ansible.builtin.shell: rustup-init --default-host x86_64-unknown-linux-gnu --profile default --default-toolchain stable -y
  become: true 
  become_user: "{{ primary_user }}"

- name: Install cargo binaries 
  community.general.cargo:
    name:  river-bsp-layout 
    locked: true
    executable: "/home/{{ primary_user }}/.cargo/bin/cargo"
    path: "/home/{{ primary_user }}/.cargo"
  become: true 
  become_user: "{{ primary_user }}"
