- name: Install base packages 
  community.general.pacman:
    name: 
      - alacritty
      - base-devel
      - dunst
      - firefox
      - grim
      - keepassxc
      - ledger
      - libreoffice-fresh
      - neovim
      - networkmanager
      - openssh
      - openssl
      - plocate
      - papirus-icon-theme
      - pavucontrol
      - river
      - ripgrep
      - rustup
      - otf-cascadia-code-fonts
      - swaybg
      - swayidle
      - swaylock
      - torbrowser-launcher 
      - unzip
      - vlc
      - waybar
      - wlr-randr
      - xeyes
      - xwayland
      - zip
      - zsh
    state: latest

- name: Remove unneeded packages 
  community.general.pacman:
    name:
      - blueman
      - bluez
      - xdg-desktop-portal-gtk
    state: absent

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"
  when: '"zsh" in shell'

- name: Install Zsh Autosuggestions 
  ansible.builtin.shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  args: 
    creates: "/home/{{ primary_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ primary_user }}"
  when: '"zsh" in shell'

- name: Install Tailscale 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://tailscale.com/install.sh)"
  args:
    creates: "/usr/bin/tailscale"

- name: Setup Rust 
  ansible.builtin.shell: rustup default stable
  become: true
  become_user: "{{ primary_user }}"

- name: Install river-bsp-layout 
  ansible.builtin.shell: cargo install river-bsp-layout --locked
  become: true 
  become_user: "{{ primary_user }}"
