- name: Install base packages 
  ansible.builtin.dnf:
    name: 
      - alacritty
      - blueman
      - bluez
      - dunst
      - firefox
      - grim
      - keepassxc
      - libreoffice
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - pavucontrol
      - river
      - ripgrep
      - rofi-wayland
      - cascadia-code-pl-fonts
      - swaybg
      - swayidle
      - swaylock
      - torbrowser-launcher 
      - vlc
      - waybar
      - wlr-randr
      - xorg-x11-server-Xwayland
      - zsh
    state: latest

