- name: Install base packages 
  ansible.builtin.dnf:
    name: 
      - alacritty
      - blueman
      - bluez
      - dunst
      - firefox
      - grim
      - keepassxc
      - ledger
      - libreoffice
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pavucontrol
      - river
      - ripgrep
      - rofi-wayland
      - cascadia-code-pl-fonts
      - swaybg
      - swayidle
      - swaylock
      - torbrowser-launcher 
      - unzip
      - vlc
      - waybar
      - wlr-randr
      - xorg-x11-server-Xwayland
      - zip
      - zsh
    state: latest

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/aj/.oh-my-zsh/oh-my-zsh.sh
  become: true
  become_user: aj

- name: Install Zsh Autosuggestions 
  ansible.builtin.shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  args: 
    creates: /home/aj/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: true
  become_user: aj
