- name: Install base packages 
  ansible.builtin.dnf:
    name: 
      - alacritty
      - blueman
      - bluez
      - dunst
      - firefox
      - grim
      - keepassxc
      - libreoffice
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - pavucontrol
      - river
      - ripgrep
      - rofi-wayland
      - cascadia-code-pl-fonts
      - swaybg
      - swayidle
      - swaylock
      - torbrowser-launcher 
      - vlc
      - waybar
      - wlr-randr
      - xorg-x11-server-Xwayland
      - zsh
    state: latest

- name: Install Oh-My-Zsh 
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install Zsh Autosuggestions 
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
