- name: Install base packages 
  ansible.builtin.dnf:
    name: 
      - alacritty
      - blueman
      - bluez
      - dunst
      - grim
      - keepassxc
      - ledger
      - libreoffice
      - MozillaFirefox
      - MozillaFirefox-branding-upstream
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pavucontrol
      - river
      - ripgrep
      - rofi-wayland
      - saja-cascadia-code-fonts
      - swaybg
      - swayidle
      - swaylock
      - torbrowser-launcher 
      - unzip
      - vlc
      - waybar
      - wlr-randr
      - xwayland
      - zip
      - zsh
    state: latest

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"
  when: '"zsh" in shell'

- name: Install Zsh Autosuggestions 
  ansible.builtin.shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  args: 
    creates: "/home/{{ primary_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ primary_user }}"
  when: '"zsh" in shell'

