- name: Add tailscale repo 
  ansible.builtin.yum_repository:
    name: tailscale 
    description: Tailscale repo 
    async: true 
    baseurl: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    enabled: true 
    state: present 
    gpgcheck: true 
    repo_gpgcheck: true

- name: Install base packages 
  ansible.builtin.dnf:
    name: 
      - alacritty
      - blueman
      - bluez
      - cascadia-code-pl-fonts
      - dunst
      - firefox
      - gvfs-mtp
      - grim
      - jmtpfs
      - keepassxc
      - ledger
      - libreoffice
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pavucontrol
      - river
      - ripgrep
      - rofi-wayland
      - swaybg
      - swayidle
      - swaylock
      - tailscale
      - thunar
      - torbrowser-launcher 
      - unzip
      - vlc
      - waybar
      - wlr-randr
      - xorg-x11-server-Xwayland
      - zip
      - zsh
      - zsh-autosuggestions
    state: latest

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"

