---

- name: Add tailscale repo 
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    async: true 
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    enabled: true 
    state: present 
    gpgcheck: true 
    repo_gpgcheck: true 
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg

- name: Import RPM Fusion GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop:
    - "https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Enable the RPM Fusion repository
  ansible.builtin.dnf:
    name: 
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Enable river-bsp-layout copr repo 
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:areif-dev:river-bsp-layout 
    description: Copr repo for river-bsp-layout owned by areif-dev 
    baseurl: https://download.copr.fedorainfracloud.org/results/areif-dev/river-bsp-layout/fedora-$releasever-$basearch/
    skip_if_unavailable: true 
    gpgcheck: true 
    gpgkey: https://download.copr.fedorainfracloud.org/results/areif-dev/river-bsp-layout/pubkey.gpg
    repo_gpgcheck: false
    enabled: true 
    async: true
