--- 

- name: Change hostname 
  ansible.builtin.hostname: 
    name: "{{ hostname }}"

      # - name: Speed up DNF
      #   ansible.builtin.ini_file:
      #     path: /etc/dnf/dnf.conf  # Adjust the path if needed
      #     section: main
      #     option: "{{ item.option }}"
      #     value: "{{ item.value }}"
      #   loop:
      #     - { option: 'max_parallel_downloads', value: '15' }
      #     - { option: 'fastestmirror', value: 'True' }
