--- 

- name: Change hostname 
  ansible.builtin.hostname: 
    name: "{{ hostname }}"

- name: Remove YaST2 From App Menu 
  ansible.builtin.file:
    state: absent
    path: /usr/share/applicatons/YaST2/
