--- 

- name: Change hostname 
  ansible.builtin.hostname: 
    name: "{{ hostname }}"

- name: Create primary_user and assign preferred shell
  user:
    name: "{{ primary_user }}"
    shell: "{{ shell }}"

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ primary_user }}/.oh-my-zsh/oh-my-zsh.sh"
  become: true
  become_user: "{{ primary_user }}"
  when: shell == "/usr/bin/zsh"
