- name: Create Ansible user
  user:
    name: ansible
    system: yes

- name: Copy sudoers_ansible 
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Create primary_user and assign preferred shell
  user:
    name: "{{ primary_user }}"
    shell: "{{ shell }}"
