- name: Save old sources 
  ansible.builtin.command:
    cmd: mv /etc/apt/sources.list /etc/apt/source.list.bak 
    removes: /etc/apt/sources.list 
    creates: /etc/apt/sources.list.bak

- name: Create sources for sid
  ansible.builtin.deb822_repository: 
    name: unstable
    types: 
      - deb 
      - deb-src
    uris: https://ftp.debian.org/debian/
    suites: sid
    components: 
      - contrib 
      - main 
      - non-free 
      - non-free-firmware 
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Create sources for tailscale 
  ansible.builtin.deb822_repository: 
    name: tailscale 
    types: deb 
    uris: https://pkgs.tailscale.com/stable/debian
    suites: sid 
    components: main 
    signed_by: https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg

- name: Run apt-get update
  ansible.builtin.command: apt-get update

- name: Full upgrade if switching to Sid for the first time
  ansible.builtin.command: 
    cmd: apt-get -y full-upgrade
    creates: /var/local/migration-complete

- name: Mark Sid migration as complete
  ansible.builtin.file:
    path: /var/local/migration-complete
    state: touch

- name: Install packages 
  ansible.builtin.apt:
    state: latest
    name:
      - alacritty 
      - bc 
      - bluez 
      - bluez-tools 
      - build-essential
      - cups
      - dbus 
      - dbus-daemon 
      - distrobox 
      - dunst 
      - ffmpeg
      - firefox 
      - fonts-cascadia-code
      - fonts-font-awesome
      - fonts-noto
      - gamemode
      - gimp
      - gnome-keyring 
      - grim 
      - gvfs
      - hledger 
      - htop
      - hyprland
      - jmtpfs 
      - jq 
      - keepassxc
      - libguestfs-tools 
      - libreoffice
      - libvirt-daemon
      - libvirt-daemon-config-network 
      - lxpolkit 
      - manpages 
      - mtp-tools
      - neovim 
      - nodejs 
      - network-manager
      - nvtop 
      - nwg-look
      - openssl 
      - papirus-icon-theme 
      - pavucontrol 
      - pipewire 
      - playerctl 
      - plocate 
      - podman
      - podman-compose
      - python3 
      - python3-guestfs 
      - python3-pip 
      - qemu-kvm 
      - remmina
      - ripgrep 
      - rustup 
      - sqlite3 
      - ssh
      - steam-installer
      - swaybg 
      - swayidle 
      - swaylock 
      - system-config-printer
      - tailscale
      - thunar 
      - thunar-archive-plugin 
      - thunar-volman 
      - thunderbird
      - unzip 
      - virt-install 
      - virt-manager 
      - virt-top 
      - virt-viewer 
      - vlc  
      - waybar 
      - wireplumber 
      - wl-clipboard 
      - wlr-randr 
      - xdg-desktop-portal-hyprland
      - xdg-user-dirs 
      - xwayland
      - zip 
      - zsh 
      - zsh-autosuggestions 

- name: Uninstall software 
  ansible.builtin.apt:
    state: absent 
    name:
      - foot 
      - gnome-boxes 
      - xdg-desktop-portal-wlr 
      - river
      - ranger 
      - openvpn
      - krita 
      - cockpit

- name: Update User Dirs 
  ansible.builtin.shell:
    cmd: xdg-user-dirs-update 
  become_user: "{{ primary_user }}"

# - name: Add development distrobox
#   ansible.builtin.shell: distrobox create --pull --image ghcr.io/areif-dev/distrobox-images/fedora-dev:latest --name dev
#   become_user: "{{ primary_user }}"

- name: Install Rust 
  ansible.builtin.shell: 
    cmd: scripts/rust.sh
    creates: "/home/{{ primary_user }}/.cargo/bin/cargo"
  become_user: "{{ primary_user }}"

- name: Install gtk theme 
  ansible.builtin.shell: 
    cmd: scripts/gtk.sh
    creates: "/home/{{ primary_user }}/.themes/gtk-installed"
  become_user: "{{ primary_user }}"

- name: Install phinger cursors 
  ansible.builtin.shell:
    cmd: scripts/phinger-cursors.sh
    creates: "/home/{{ primary_user }}/.icons/phinger-installed"
  become_user: "{{ primary_user }}"

- name: Install Oh My Zsh 
  ansible.builtin.shell:
    cmd: scripts/ohmyz.sh 
    creates: "/home/{{ primary_user }}/.oh-my-zsh/ohmyzsh-installed"
  become_user: "{{ primary_user }}"

- name: Install Starship Prompt 
  ansible.builtin.shell:
    cmd: scripts/starship.sh 
    creates: "/usr/bin/starship"
